// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyEkeTObgIG60l4Hoc1aFTce1mrGQGXPs',
    appId: '1:382305010081:web:7709c7002a97f10b3a0be0',
    messagingSenderId: '382305010081',
    projectId: 'database-ce78d',
    authDomain: 'database-ce78d.firebaseapp.com',
    databaseURL: 'https://database-ce78d-default-rtdb.firebaseio.com',
    storageBucket: 'database-ce78d.appspot.com',
    measurementId: 'G-BF9SSNMKF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJz_YKgqulcHvcJMbF0nXz5XERWV_zII',
    appId: '1:382305010081:android:1aa1ebb9fc31e2493a0be0',
    messagingSenderId: '382305010081',
    projectId: 'database-ce78d',
    databaseURL: 'https://database-ce78d-default-rtdb.firebaseio.com',
    storageBucket: 'database-ce78d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSdiRaSUhiUlDq1HMsNnY_A1mJFngUrQ',
    appId: '1:382305010081:ios:dd8a1d1345fc212c3a0be0',
    messagingSenderId: '382305010081',
    projectId: 'database-ce78d',
    databaseURL: 'https://database-ce78d-default-rtdb.firebaseio.com',
    storageBucket: 'database-ce78d.appspot.com',
    androidClientId: '382305010081-igifv735mk8s8nf16ivr2b08rig3df1j.apps.googleusercontent.com',
    iosClientId: '382305010081-ro08vjip90tfa30pc4op0mbdshsnc2rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANSdiRaSUhiUlDq1HMsNnY_A1mJFngUrQ',
    appId: '1:382305010081:ios:1a91363abbec0e5a3a0be0',
    messagingSenderId: '382305010081',
    projectId: 'database-ce78d',
    databaseURL: 'https://database-ce78d-default-rtdb.firebaseio.com',
    storageBucket: 'database-ce78d.appspot.com',
    androidClientId: '382305010081-igifv735mk8s8nf16ivr2b08rig3df1j.apps.googleusercontent.com',
    iosClientId: '382305010081-51mjjgf804dp3s2ril664oar2ejoo78l.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopAdmin.RunnerTests',
  );
}
